name: "Default Clusters"
packageKey: "br.com.wesley.betabeta.default-clusters"
description: "This driver is intended to work with devices that use standard zigbee clusters"
vendorSupportInformation: 'This driver requires firmware 45.1+ to work properly.<br /><br /><a href="https://community.smartthings.com/t/st-edge-personal-tuya-devices-generic-ef00-device/255270?u=w35l3y">SmartThings Community discussion</a><br /><br /><a href="https://github.com/w35l3y/EdgeDrivers/tree/main/default-clusters#readme">GitHub Repository</a>'
permissions:
  zigbee: {}
