# ./smartthings presentation:device-config:create -y -i=personal-tuya-devices/presentations/custom-multi-dimmer-v2.yaml -o=personal-tuya-devices/presentations/custom-multi-dimmer-v2.yaml
mnmn: SmartThingsCommunity
vid: 94459380-339b-3a1a-951b-b010e0a9e54c
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
      values: []
      composite: true
    - component: main01
      capability: switch
      version: 1
      idx: 0
      group: Dimmer 1
      values: []
      composite: true
    - component: main02
      capability: switch
      version: 1
      idx: 0
      group: Dimmer 2
      values: []
      composite: true
  actions:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
      inline: null
    - component: main01
      capability: switch
      version: 1
      idx: 0
      group: Dimmer 1
      inline: null
    - component: main02
      capability: switch
      version: 1
      idx: 0
      group: Dimmer 2
      inline: null
  basicPlus: []
detailView:
  - component: main
    capability: switch
    version: 1
    values: []
    patch: []
  - component: main
    capability: switchLevel
    version: 1
    values: []
    patch: []
  - component: main
    capability: signalStrength
    version: 1
    values: []
    patch: []
  - component: main01
    capability: switch
    version: 1
    values: []
    patch: []
  - component: main01
    capability: switchLevel
    version: 1
    values: []
    patch: []
  - component: main01
    capability: valleyboard16460.datapointEnum
    version: 1
    values: []
    patch: []
  - component: main02
    capability: switch
    version: 1
    values: []
    patch: []
  - component: main02
    capability: switchLevel
    version: 1
    values: []
    patch: []
  - component: main02
    capability: valleyboard16460.datapointEnum
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: switchLevel
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main01
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main01
      capability: switchLevel
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main02
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main02
      capability: switchLevel
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: main
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: switchLevel
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main01
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main01
      capability: switchLevel
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main02
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main02
      capability: switchLevel
      version: 1
      values: []
      patch: []
      exclusion: []
presentationId: 94459380-339b-3a1a-951b-b010e0a9e54c
manufacturerName: SmartThingsCommunity
