# ./smartthings presentation:device-config:create -y -i=personal-tuya-devices/presentations/custom-multi-dimmer-v2.yaml -o=personal-tuya-devices/presentations/custom-multi-dimmer-v2.out.yaml
mnmn: SmartThingsCommunity
vid: 417c33a0-9b77-3754-88f8-ac7feba6a22f
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
      values: []
      composite: true
    - component: main01
      capability: switch
      version: 1
      idx: 0
      group: Switch 1
      values: []
      composite: true
    - component: main07
      capability: switch
      version: 1
      idx: 0
      group: Switch 2
      values: []
      composite: true
  actions:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
      inline: null
    - component: main01
      capability: switch
      version: 1
      idx: 0
      group: Switch 1
      inline: null
    - component: main07
      capability: switch
      version: 1
      idx: 0
      group: Switch 2
      inline: null
  basicPlus: []
detailView:
  - component: main
    capability: switch
    version: 1
    values: []
    patch: []
  - component: main01
    capability: switch
    version: 1
    values: []
    patch: []
  - component: main02
    capability: switchLevel
    version: 1
    values: []
    patch: []
  - component: main03
    capability: switchLevel
    version: 1
    values: []
    patch: []
  - component: main04
    capability: valleyboard16460.datapointEnum
    version: 1
    values: []
    patch: []
  - component: main07
    capability: switch
    version: 1
    values: []
    patch: []
  - component: main08
    capability: switchLevel
    version: 1
    values: []
    patch: []
  - component: main09
    capability: switchLevel
    version: 1
    values: []
    patch: []
  - component: main0A
    capability: valleyboard16460.datapointEnum
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main01
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main02
      capability: switchLevel
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main07
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main08
      capability: switchLevel
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: main
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main01
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main02
      capability: switchLevel
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main07
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main08
      capability: switchLevel
      version: 1
      values: []
      patch: []
      exclusion: []
presentationId: 417c33a0-9b77-3754-88f8-ac7feba6a22f
manufacturerName: SmartThingsCommunity
