#./smartthings capabilities:presentation:create valleyboard16460.datapointString 1 -y -i=personal-tuya-devices/presentations/datapointString.yaml -o=personal-tuya-devices/presentations/datapointString.out.yaml
#./smartthings capabilities:presentation:update valleyboard16460.datapointString 1 -y -i=personal-tuya-devices/presentations/datapointString.yaml -o=personal-tuya-devices/presentations/datapointString.out.yaml
dashboard:
  states:
    - label: "{{value.value}}"
  actions: []
detailView:
  - label: Datapoint String
    displayType: textField
    textField:
      command: setValue
      argumentType: string
      value: value.value
      valueType: string
automation:
  conditions:
    - label: Datapoint String
      displayType: textField
      textField:
        value: value.value
        valueType: string
  actions:
    - label: Datapoint String
      displayType: textField
      textField:
        command: setValue
        argumentType: string
id: valleyboard16460.datapointString
version: 1
