name: call-update-templates-common

on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        required: true
        type: string
        default: beta
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: string
        default: beta

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: md files
        uses: varunsridharan/action-dynamic-readme@main
        with:
          files: |
            TEMPLATE.md=README.md
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
          commit_message: "docs: update readme file [skip ci]"
        env:
          INVITATION_LINK: ${{ vars.INVITATION_LINK }}
          INVITATION_LINK_BETA: ${{ vars.INVITATION_LINK_BETA }}
          ENVIRONMENT: ${{ inputs.environment }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
