name: call-publish-driver

on:
  workflow_call:
    inputs:
      driver:
        description: "Folder name of the driver"
        required: true
        type: string
      environment:
        description: Environment
        required: true
        type: string
        default: beta
  workflow_dispatch:
    inputs:
      driver:
        description: "Folder name of the driver"
        required: true
        type: string
      environment:
        description: Environment
        required: true
        type: string
        default: beta

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Install Lua
        run: |
          sudo apt update
          sudo apt install lua5.3
      - name: Load SmartThings API from cache
        uses: actions/cache@v3
        id: stapi
        with:
          path: lua_libs-api_v*
          key: stapi-lua_libs-api_v3_46X
      - name: Download SmartThings API
        if: steps.stapi.outputs.cache-hit != 'true'
        run: wget https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/releases/latest/download/lua_libs-api_v3_46X.tar.gz -O - | tar -xz
      - name: Set LUA_PATH
        run: echo "LUA_PATH=$(pwd)/lua_libs-api_v3/?.lua;$(pwd)/lua_libs-api_v3/?/init.lua;./?.lua;./?/init.lua;;" >> $GITHUB_ENV
      - name: Set ST_CAPABILITY_CACHE
        run: echo "ST_CAPABILITY_CACHE=$(pwd)/capabilities/" >> $GITHUB_ENV
      - name: Create symbolic link
        run: sudo ln -s $(pwd)/smartthings /usr/bin/smartthings
      - name: Run tests
        id: test
        working-directory: ${{ inputs.driver }}/src
        run: lua test/switch.lua | awk -v x=1 '/SUCCESS/{x=0}END{exit x}' -
        # run: echo "success=$(lua test/switch.lua | awk '/SUCCESS/{print("true");f=1}END{if(!f)print("false")}' -)" >> $GITHUB_OUTPUT
      - name: Check test
        run: echo "result = ${{ steps.test.outputs.success }} (${{ steps.test.outputs.success == 'true' }})"
      # - name: Load SmartThings CLI from cache
      #   uses: actions/cache@v3
      #   id: stcli
      #   with:
      #     path: smartthings
      #     key: stcli-latest
      # - name: Download SmartThings CLI
      #   if: steps.stcli.outputs.cache-hit != 'true'
      #   run: wget https://github.com/SmartThingsCommunity/smartthings-cli/releases/latest/download/smartthings-linux-x64.tar.gz -O - | tar -xz
      # - name: Publish
      #   run: smartthings edge:drivers:package ${{ inputs.driver }} --channel=${{ secrets.SMARTTHINGS_CHANNEL }}
      #   env:
      #     SMARTTHINGS_TOKEN: ${{ secrets.SMARTTHINGS_TOKEN }}
