name: call-publish-driver

on:
  workflow_call:
    inputs:
      driver:
        description: "Folder name of the driver"
        required: true
        type: string
      environment:
        description: Environment
        required: true
        type: string
        default: beta
  workflow_dispatch:
    inputs:
      driver:
        description: "Folder name of the driver"
        required: true
        type: string
      environment:
        description: Environment
        required: true
        type: string
        default: beta

jobs:
  test:
    uses: ./.github/workflows/call-test-driver.yaml
    with:
      driver: ${{ inputs.driver }}
      environment: ${{ inputs.environment }}
    secrets: inherit
  publish:
    needs: test
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
    steps:
      - name: Check SMARTTHINGS_TOKEN
        uses: actions/github-script@v3
        if: secrets.SMARTTHINGS_TOKEN == ''
        with:
          script: |
            core.setFailed("Missing SMARTTHINGS_TOKEN")
      - name: Check SMARTTHINGS_CHANNEL
        uses: actions/github-script@v3
        if: secrets.SMARTTHINGS_CHANNEL == ''
        with:
          script: |
            core.setFailed("Missing SMARTTHINGS_CHANNEL")
      - uses: actions/checkout@v3
      - name: Load node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Execute helpers
        run: |
          npm ci
          npm start
      - name: Remove unwanted files before packaging
        working-directory: ${{ inputs.driver }}/src
        run: |
          find . -name "*.md" -type f -delete
      - name: Load SmartThings CLI from cache
        uses: actions/cache@v3
        id: stcli
        with:
          path: smartthings
          key: stcli-latest
      - name: Download SmartThings CLI
        if: steps.stcli.outputs.cache-hit != 'true'
        run: wget https://github.com/SmartThingsCommunity/smartthings-cli/releases/latest/download/smartthings-linux-x64.tar.gz -O - | tar -xz
      - name: Set Environment Variables
        run: |
          echo "$(pwd)" >> $GITHUB_PATH
      - name: Publish
        run: smartthings edge:drivers:package ${{ inputs.driver }} --channel=${{ vars.SMARTTHINGS_CHANNEL }}
        env:
          SMARTTHINGS_TOKEN: ${{ secrets.SMARTTHINGS_TOKEN }}
