name: package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: download smartthings-cli
        run: wget https://github.com/SmartThingsCommunity/smartthings-cli/releases/latest/download/smartthings-linux-x64.tar.gz -O - | tar -xz
      - name: package personal-tuya-devices
        run: smartthings edge:drivers:package personal-tuya-devices
      - name: package zigbee-smart-plug
        run: smartthings edge:drivers:package zigbee-smart-plug
