name: publish-update-readme

on:
  push:
    branches:
      - main
      - beta
    paths:
      - "personal-tuya-devices/TEMPLATE.md"
  pull_request:
    branches:
      - main
      - beta
    paths:
      - "personal-tuya-devices/TEMPLATE.md"

jobs:
  call:
    uses: ./.github/workflows/call-update-readme.yaml
    with:
      driver: personal-tuya-devices
      environment: ${{ github.head_ref || github.ref_name }}
    secrets: inherit
