name: publish-update-templates

on:
  push:
    branches:
      - main
      - beta
    paths:
      - "default-clusters/TEMPLATE.md"
      - "default-clusters/config-TEMPLATE.yaml"

jobs:
  common:
    uses: ./.github/workflows/call-update-templates-common.yaml
    with:
      environment: ${{ github.head_ref || github.ref_name }}
    secrets: inherit
  update_driver_version:
    uses: ./.github/workflows/call-update-templates.yaml
    with:
      driver: default-clusters
      version: all
      environment: ${{ github.head_ref || github.ref_name }}
    secrets: inherit
