name: publish-default-clusters

on:
  push:
    branches:
      - main
      - beta
    paths:
      - "default-clusters/**.yaml"
      - "default-clusters/src/**.lua"

jobs:
  call:
    uses: ./.github/workflows/call-publish-driver.yaml
    with:
      driver: default-clusters
      environment: ${{ github.head_ref || github.ref_name }}
    secrets: inherit
