name: publish

on:
  workflow_call:
    inputs:
      driver:
        description: "Folder name of the driver"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: download smartthings-cli
        run: wget https://github.com/SmartThingsCommunity/smartthings-cli/releases/latest/download/smartthings-linux-x64.tar.gz -O - | tar -xz
      - name: publish
        run: ./smartthings edge:drivers:package ${{ inputs.driver }} --channel=665ba729-1a23-4183-9d38-746a44175978
        env:
          SMARTTHINGS_TOKEN: ${{ secrets.SMARTTHINGS_TOKEN }}
