name: publish-update-templates

on:
  push:
    branches:
      - main
      - beta
    paths:
      - "TEMPLATE.md"
      - "default-clusters/TEMPLATE.md"
      - "default-clusters/config-TEMPLATE.yml"
      - "personal-tuya-devices/TEMPLATE.md"
      - "personal-tuya-devices/config-TEMPLATE.yml"
  pull_request:
    branches:
      - main
      - beta
    paths:
      - "TEMPLATE.md"
      - "default-clusters/TEMPLATE.md"
      - "default-clusters/config-TEMPLATE.yml"
      - "personal-tuya-devices/TEMPLATE.md"
      - "personal-tuya-devices/config-TEMPLATE.yml"

jobs:
  tuya_devices:
    uses: ./.github/workflows/call-update-templates.yaml
    with:
      driver: personal-tuya-devices
      environment: ${{ github.head_ref || github.ref_name }}
    secrets: inherit
  default_clusters:
    needs: tuya_devices
    uses: ./.github/workflows/call-update-templates.yaml
    with:
      driver: default-clusters
      environment: ${{ github.head_ref || github.ref_name }}
    secrets: inherit
