name: publish-update-templates

on:
  push:
    branches:
      - main
      - beta
    paths:
      - "TEMPLATE.md"
      - "personal-tuya-devices/TEMPLATE.md"

jobs:
  common:
    uses: ./.github/workflows/call-update-templates-common.yaml
    with:
      environment: ${{ github.head_ref || github.ref_name }}
    secrets: inherit
