name: test-personal-tuya-devices

on:
  pull_request:
    branches:
      - main
      - beta
    paths:
      - "personal-tuya-devices/**.yaml"
      - "personal-tuya-devices/src/**.lua"

jobs:
  call:
    uses: ./.github/workflows/call-test-driver.yaml
    with:
      driver: personal-tuya-devices
      environment: ${{ github.head_ref || github.ref_name }}
    secrets: inherit
